language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: e47f50d3aa20c206daeb257d390b18a444613ef4e1e6b29a6f420165c838ad3c
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: gQIIwnB9yjue/9Kxep/Al6yZsB4Tcz1QcD3uGDUXkHiVRsMZsBAgJGJ52xpnPd/uL8YYvz3mDXo6G6d7iAKgQRUbNvIjRnJ6WnOa+h0v87qk87+NBfcVTbgyRhAunfTpCnknDlaKSYBbM14AKSNve8DWbgSmf/Bl5yCJhifwN/W2Pq8JD1//XDIrt8HxcdoYwYGnuGqKRXSVI4vcSaJ7mKiTpQkDvD9X2vka++HhpuLqLO02g6/IPZXtfb0UMWN1pNKcS2UtzvLNhlui4/UB1dGuxe+RCGjoVA4pTWw1dtMbTgMsVZilhiZgnj8LJHPLkkOun6mbp2FwfJTIgx7OECpfk98f9N/XsUR5yn0PmZJqb4gzpE8ofcH+YXT1NCxD/TzZnGraBwr8IlmkiJvoXWYG5KZxCWdSea3/2QZk/F6s/x8wqVFvQM3wLfBwbBuflfZItc3zWRsUsO/PpL4g49MkMriu7NO3uFtBkw7J0XgJMdcSYCYerYnByoNRlPABaSdOXz/5Y3fB38Vk2l+V8iwoxn/iPn26Wt/Z9q4W4Lk9qx8GFcoW1h2SeTXVtfeUHO/Kd0zsOg8bkSL9PieHrkl5O+6noJmcFap0fNrtvGCx1dZPNSV4EBNUCFropyUQO7POE2pWgr3ROiqWCx4lkm9fU9f0k6rzMvogW+jGsFQ=
  on:
    tags: true
    repo: yoctore/yocto-router
before_install: npm install -g grunt-cli
install: npm install
